// Generated static Traditional Chinese identity copy. No runtime translation request.
export default {
  "Send reset code": "傳送重置驗證碼",
  "Reset password & sign in": "重置密碼並登入",
  "Verify & continue": "驗證並繼續",
  "Create password & sign in": "設定密碼並登入",
  "Send secure code": "傳送安全驗證碼",
  "Continue with password": "使用密碼繼續",
  "Use another email": "更換電子郵件",
  "Use password instead": "改用密碼",
  "Use an email code instead": "改用電子郵件驗證碼",
  "Sign-in is still loading.": "登入功能仍在載入。",
  "That code is incorrect. Please try again.": "驗證碼不正確，請重試。",
  "That code expired. Request a new one.": "驗證碼已過期，請重新發送。",
  "No account exists with that email.": "未找到使用該電子郵件的帳戶。",
  "That password is incorrect.": "密碼不正確。",
  "Your password must be at least 8 characters.": "密碼至少需要 8 個字元。",
  "Request failed. Please try again later.": "請求失敗，請稍後重試。",
  "Request failed.": "請求失敗。",
  "Your email is verified. Create a password to finish signing in.": "電子郵件已驗證。請設定密碼以完成登入。",
  "Your account requires additional information before sign-in can finish. Use another sign-in method or contact an administrator.": "帳戶仍需補充資料才能完成登入。請更換登入方式或聯絡管理員。",
  "This account requires another security factor. Contact an administrator.": "此帳戶需要其他安全驗證，請聯絡管理員。",
  "This device needs extra verification. A new security code was sent to {identifier}": "此裝置需要額外驗證，新的安全碼已傳送至 {identifier}",
  "Sign-in needs another step ({status}).": "登入需要額外步驟（{status}）。",
  "unknown": "未知",
  "Account found. Check {identifier} and enter the one-time reset code from the email.": "帳戶已找到。請檢查 {identifier}，並輸入郵件中的一次性重置驗證碼。",
  "Your new password must be at least 8 characters.": "新密碼至少需要 8 個字元。",
  "The new passwords do not match.": "兩次輸入的新密碼不一致。",
  "Code sent to {identifier}": "驗證碼已傳送至 {identifier}",
  "The passwords do not match.": "兩次輸入的密碼不一致。",
  "Enter your account email to receive a one-time reset code.": "輸入帳戶電子郵件以接收一次性重置驗證碼。",
  "Connecting your secure session…": "正在連線安全會話…",
  "Unable to connect your secure session.": "無法建立安全會話。",
  "Email address": "電子郵件",
  "Password": "密碼",
  "New password": "新密碼",
  "Confirm new password": "確認新密碼",
  "Forgot password?": "忘記密碼？",
  "One-time code": "一次性驗證碼",
  "If you don't see the code email in your inbox, check your Spam or Junk folder.": "如果收件箱中沒有看到驗證碼郵件，請檢查垃圾郵件或廣告郵件資料夾。",
  "Self-service recovery cannot work if the account email is false or unreachable.": "若註冊電子郵件不存在或無法收信，將無法自行找回密碼。",
  "Please wait…": "請稍候…",
  "Your password was not changed because identity confirmation was cancelled.": "身份確認已取消，密碼沒有更改。",
  "Your current password is incorrect.": "當前密碼不正確。",
  "Confirm your identity to save the password, then try again.": "請先完成身份確認，再儲存密碼。",
  "Could not save your password. Please try again.": "無法儲存密碼，請重試。",
  "Your account is not ready.": "帳戶尚未載入。",
  "Enter your current password.": "請輸入當前密碼。",
  "Password saved. You can sign in with a password or an email code.": "密碼已儲存。以後可使用密碼或電子郵件驗證碼登入。",
  "ACCOUNT SECURITY": "帳戶安全",
  "Update password": "更新密碼",
  "Add password": "新增密碼",
  "Enter your current password. If this sign-in is no longer recent, a secure identity confirmation will appear before saving.": "輸入當前密碼即可更改；如果本次登入已超過安全時限，儲存前會出現安全身份確認。",
  "Add a password from this signed-in session. A recent email-code sign-in needs no extra code, and both sign-in methods will remain available.": "從當前已登入會話新增密碼；近期使用電子郵件驗證碼登入無需再次輸入驗證碼，新增後兩種登入方式都會保留。",
  "Loading account…": "正在讀取帳戶…",
  "Current password": "當前密碼",
  "At least 8 characters. Use a unique password that you do not use on other sites.": "至少 8 個字元；請使用未在其他網站重複使用的密碼。",
  "Saving…": "正在儲存…",
  "Show password": "顯示密碼",
  "Hide password": "隱藏密碼"
} as Record<string, string>;
