import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
const css=readFileSync(new URL("../app/text-containment.css",import.meta.url),"utf8");
const layout=readFileSync(new URL("../app/layout.tsx",import.meta.url),"utf8");
const globalCss=readFileSync(new URL("../app/globals.css",import.meta.url),"utf8");
const viewportWidths=[390,430,820,1180,1440];
function finalBoxStyle(source,selector){source=source.replace(/\/\*[\s\S]*?\*\//g,"");const style={};for(const match of source.matchAll(/([^{}]+)\{([^{}]*)\}/g)){if(!match[1].split(",").map(value=>value.trim()).includes(selector))continue;for(const declaration of match[2].matchAll(/([\w-]+)\s*:\s*([^;!]+)(?:!important)?\s*;?/g)){const property=declaration[1];const value=declaration[2].trim();if(property==="width"||property==="inline-size")style.inlineSize=value;if(property==="max-width"||property==="max-inline-size")style.maxInlineSize=value}}return style}
function resolveLength(value,parent){if(!value||value==="auto"||value==="100%")return parent;if(value==="none")return Number.POSITIVE_INFINITY;const pixels=value.match(/^(\d+(?:\.\d+)?)px$/);if(pixels)return Number(pixels[1]);throw new Error(`Unsupported deterministic width: ${value}`)}
function assertFullSurface(label,parent,style){const used=Math.min(resolveLength(style.inlineSize,parent),resolveLength(style.maxInlineSize??"none",parent));const scrollWidth=Math.max(parent,used);assert.ok(scrollWidth<=parent+.01,`${label}: scrollWidth <= clientWidth`);assert.ok(Math.abs(used-parent)<=1,`${label}: ${used}px fills ${parent}px track`)}
test("text containment is the final global CSS layer",()=>{const imports=[...layout.matchAll(/import "(\.\/[^"]+\.css)";/g)].map(m=>m[1]);assert.equal(imports.at(-1),"./text-containment.css")});
test("layout text fits its owning container without page-level clipping",()=>{assert.match(css,/min-inline-size:\s*0/);assert.match(css,/overflow-wrap:\s*anywhere/);assert.match(css,/text-wrap:\s*wrap/);assert.doesNotMatch(css,/text-wrap:\s*balance/);assert.match(css,/white-space:\s*normal!important/);assert.match(css,/table-layout:\s*fixed/);assert.match(css,/max-inline-size:\s*100%/);assert.doesNotMatch(css,/(?:html|body)[^{]*\{[^}]*overflow-x:\s*(?:hidden|clip)/s)});
test("phone, iPad portrait, iPad landscape, and desktop widths are explicit contract widths",()=>{assert.deepEqual(viewportWidths,[390,430,820,1180,1440]);assert.match(css,/@media \(max-width: 1180px\)/);assert.match(css,/@media \(max-width: 760px\)/);assert.match(css,/@media \(max-width: 420px\)/);assert.match(css,/font-size:clamp\(/)});
test("shared layer covers public and member surfaces",()=>{for(const path of["../app/[lang]/page.tsx","../app/[lang]/auth/[mode]/page.tsx","../app/[lang]/dashboard/page.tsx","../app/[lang]/community/page.tsx","../app/[lang]/messages/page.tsx","../app/[lang]/messages/live/[threadId]/page.tsx","../app/[lang]/assistant/page.tsx","../app/[lang]/news/page.tsx","../app/[lang]/events/page.tsx","../app/[lang]/project/page.tsx"])assert.ok(existsSync(new URL(path,import.meta.url)),path)});
test("welcome and single-column features use their full assigned panels",()=>{assert.match(globalCss,/\.hero \{[^}]*grid-template-columns: repeat\(2, minmax\(0, 1fr\)\);[^}]*column-gap: clamp\(28px, 4vw, 64px\)/s);assert.match(globalCss,/\.hero-copy \{[^}]*padding-left: 0/s);assert.match(globalCss,/\.glm-welcome-hero\{[^}]*grid-template-columns:repeat\(2,minmax\(0,1fr\)\);gap:clamp\(28px,4vw,64px\)/s);assert.match(globalCss,/@media\(max-width:1180px\)\{[\s\S]*?\.glm-welcome-hero\{[^}]*grid-template-columns:1fr/);assert.match(globalCss,/@media\(max-width:820px\)\{[\s\S]*?\.feature-grid p\{max-width:75ch\}/);assert.doesNotMatch(globalCss,/\.dashboard-page\s*\{[^}]*overflow-x\s*:/s)});
test("computed welcome copy fills the final responsive grid track",()=>{const style=finalBoxStyle(`${globalCss}\n${css}`,".hero-copy");for(const viewport of viewportWidths){const padding=viewport<=560?20:viewport<=1100?30:56;const content=Math.min(viewport,1440)-(2*padding);const gap=Math.min(64,Math.max(28,viewport*.04));const track=viewport<=1180?content:(content-gap)/2;assertFullSurface(`${viewport}px welcome copy`,track,style)}});
