import { getAdminUser } from "@/lib/admin-access";
import { getDatabase } from "@/lib/auth";
import { allCryptoPaymentSettings, normalizeTokenAmount } from "@/lib/crypto-payments";
import { getSubscriptionPlans } from "@/lib/subscription-plans";
const addressPattern=/^0x[a-fA-F0-9]{40}$/;
async function requireAdmin(request:Request){const user=await getAdminUser(request);if(!user)throw new Response(JSON.stringify({error:"Permanent administrator access required"}),{status:403,headers:{"content-type":"application/json"}});return user;}
async function prices(){const plans=await getSubscriptionPlans(),monthly=plans.find(plan=>plan.id==="monthly")?.amountCents||0,annual=plans.find(plan=>plan.id==="annual")?.amountCents||0;if(!monthly||!annual)throw new Error("PRICES_UNAVAILABLE");return{plans,monthly,annual};}
function parse(value:unknown){const input=(value||{})as Record<string,unknown>,decimals=Number(input.tokenDecimals);const result={label:String(input.label||"").trim().slice(0,80),chainName:String(input.chainName||"").trim().slice(0,50),chainId:Number(input.chainId),tokenSymbol:String(input.tokenSymbol||"").trim().toUpperCase().slice(0,12),tokenContract:String(input.tokenContract||"").trim().toLowerCase(),tokenDecimals:decimals,receiverWallet:String(input.receiverWallet||"").trim().toLowerCase(),monthlyTokenAmount:normalizeTokenAmount(input.monthlyTokenAmount,decimals),annualTokenAmount:normalizeTokenAmount(input.annualTokenAmount,decimals),minConfirmations:Number(input.minConfirmations),walletConnectProjectId:String(input.walletConnectProjectId||"").trim(),enabled:input.enabled===false?0:1};if(!result.label||!result.chainName||!result.tokenSymbol||!Number.isInteger(result.chainId)||result.chainId<=0||!addressPattern.test(result.tokenContract)||!addressPattern.test(result.receiverWallet)||!Number.isInteger(decimals)||decimals<0||decimals>18||!Number.isInteger(result.minConfirmations)||result.minConfirmations<1||result.minConfirmations>1000||(result.walletConnectProjectId&&!/^[a-fA-F0-9]{32}$/.test(result.walletConnectProjectId)))throw new Error("INVALID_SETTING");return result;}
async function audit(adminId:string,action:string,settingId:string){const now=Math.floor(Date.now()/1000);await getDatabase().prepare("INSERT INTO crypto_payment_admin_audit(id,admin_user_id,action,setting_id,created_at) VALUES(?,?,?,?,?)").bind(crypto.randomUUID(),adminId,action,settingId,now).run();}
export async function GET(request:Request){try{await requireAdmin(request);const current=await prices();return Response.json({settings:await allCryptoPaymentSettings(),plans:current.plans});}catch(error){return error instanceof Response?error:Response.json({error:"Unable to load site-local payment settings"},{status:500});}}
export async function POST(request:Request){try{const admin=await requireAdmin(request),input=parse(await request.json().catch(()=>null)),current=await prices(),id=crypto.randomUUID(),now=Math.floor(Date.now()/1000);await getDatabase().prepare(`INSERT INTO crypto_payment_settings(id,label,chain_type,chain_name,chain_id,token_symbol,token_contract,token_decimals,receiver_wallet,monthly_amount_cents,annual_amount_cents,monthly_token_amount,annual_token_amount,min_confirmations,walletconnect_project_id,enabled,created_by_user_id,created_at,updated_at) VALUES(?,?,'evm',?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,input.label,input.chainName,input.chainId,input.tokenSymbol,input.tokenContract,input.tokenDecimals,input.receiverWallet,current.monthly,current.annual,input.monthlyTokenAmount,input.annualTokenAmount,input.minConfirmations,input.walletConnectProjectId||null,input.enabled,admin.id,now,now).run();await audit(admin.id,"create",id);return Response.json({id},{status:201});}catch(error){return error instanceof Response?error:Response.json({error:"Invalid site-local crypto payment rail"},{status:400});}}
export async function PATCH(request:Request){try{const admin=await requireAdmin(request),body=await request.json().catch(()=>null)as(Record<string,unknown>&{id?:string})|null,id=String(body?.id||""),input=parse(body),current=await prices(),now=Math.floor(Date.now()/1000);if(!id)throw new Error("INVALID_SETTING");await getDatabase().prepare(`UPDATE crypto_payment_settings SET label=?,chain_name=?,chain_id=?,token_symbol=?,token_contract=?,token_decimals=?,receiver_wallet=?,monthly_amount_cents=?,annual_amount_cents=?,monthly_token_amount=?,annual_token_amount=?,min_confirmations=?,walletconnect_project_id=?,enabled=?,updated_at=? WHERE id=? AND deleted_at IS NULL`).bind(input.label,input.chainName,input.chainId,input.tokenSymbol,input.tokenContract,input.tokenDecimals,input.receiverWallet,current.monthly,current.annual,input.monthlyTokenAmount,input.annualTokenAmount,input.minConfirmations,input.walletConnectProjectId||null,input.enabled,now,id).run();await audit(admin.id,"update",id);return Response.json({updated:true});}catch(error){return error instanceof Response?error:Response.json({error:"Invalid site-local crypto payment rail"},{status:400});}}
export async function DELETE(request:Request){try{const admin=await requireAdmin(request),body=await request.json().catch(()=>null)as{id?:string}|null,id=String(body?.id||"");if(!id)return Response.json({error:"Missing rail id"},{status:400});const now=Math.floor(Date.now()/1000);await getDatabase().prepare("UPDATE crypto_payment_settings SET enabled=0,deleted_at=?,updated_at=? WHERE id=? AND deleted_at IS NULL").bind(now,now,id).run();await audit(admin.id,"delete",id);return Response.json({deleted:true});}catch(error){return error instanceof Response?error:Response.json({error:"Unable to remove payment rail"},{status:500});}}
