"use client";

import { useEffect, useState } from "react";
import type { CryptoPaymentSetting } from "@/lib/crypto-contract";
import { SUBSCRIPTION_PLANS } from "@/lib/subscription-plans";

const empty={id:"",label:"",chainName:"",chainId:"137",tokenSymbol:"USDC",tokenContract:"",tokenDecimals:"6",receiverWallet:"",monthlyTokenAmount:"5",annualTokenAmount:"8",minConfirmations:"12",walletConnectProjectId:"",enabled:true};
export default function AdminCryptoSettings({lang}:{lang:"zh"|"en"}){const[language,setLanguage]=useState<"zh"|"en">(lang);const zh=language==="zh";const[settings,setSettings]=useState<CryptoPaymentSetting[]>([]);const[form,setForm]=useState(empty);const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  async function load(){const response=await fetch("/api/admin/crypto-settings",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error);setSettings(data.settings||[]);}
  useEffect(()=>{let active=true;fetch("/api/admin/crypto-settings",{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(active)setSettings(data.settings||[]);}).catch(()=>{if(active)setMessage(zh?"无法读取收款通道。":"Unable to load payment rails.");});return()=>{active=false;};},[zh]);
  function edit(item:CryptoPaymentSetting){setForm({id:item.id,label:item.label,chainName:item.chainName,chainId:String(item.chainId),tokenSymbol:item.tokenSymbol,tokenContract:item.tokenContract,tokenDecimals:String(item.tokenDecimals),receiverWallet:item.receiverWallet,monthlyTokenAmount:item.monthlyTokenAmount,annualTokenAmount:item.annualTokenAmount,minConfirmations:String(item.minConfirmations),walletConnectProjectId:item.walletConnectProjectId||"",enabled:Boolean(item.enabled)});}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/admin/crypto-settings",{method:form.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await response.json().catch(()=>({}));if(response.ok){setForm(empty);await load();setMessage(zh?"加密收款通道已保存。":"Crypto payment rail saved.");}else setMessage(data.error||(zh?"保存失败。":"Save failed."));setBusy(false);}
  async function remove(id:string){setBusy(true);const response=await fetch("/api/admin/crypto-settings",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(response.ok){await load();setMessage(zh?"收款通道已停用并保留审计记录。":"Payment rail disabled with its audit history preserved.");}else setMessage(zh?"无法停用收款通道。":"Unable to disable payment rail.");setBusy(false);}
  const update=(key:keyof typeof empty,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
  return <section className="admin-crypto"><div><p className="eyebrow">CRYPTO PAYMENT</p><h2>{zh?"GreatLoveMeta.com 加密支付配置":"GreatLoveMeta crypto payment configuration"}</h2><p>{zh?`价格固定使用本站套餐：${SUBSCRIPTION_PLANS[0].fallbackPrice}/月、${SUBSCRIPTION_PLANS[1].fallbackPrice}/年。每条通道独立配置链、ERC-20、收款钱包、确认数和 GreatLoveMeta.com 自己的 WalletConnect 项目标识。`:`Prices use this site's plans: ${SUBSCRIPTION_PLANS[0].fallbackPrice}/month and ${SUBSCRIPTION_PLANS[1].fallbackPrice}/year. Each rail independently configures its chain, ERC-20 token, receiver, confirmations, and GreatLoveMeta-specific WalletConnect Project ID.`}</p><button type="button" onClick={()=>setLanguage(value=>value==="zh"?"en":"zh")}>{zh?"English":"中文"}</button></div>
    <form onSubmit={save}><label>{zh?"显示名称":"Label"}<input value={form.label} onChange={e=>update("label",e.target.value)} required/></label><label>{zh?"链名称":"Chain name"}<input value={form.chainName} onChange={e=>update("chainName",e.target.value)} required/></label><label>Chain ID<input inputMode="numeric" value={form.chainId} onChange={e=>update("chainId",e.target.value)} required/></label><label>{zh?"代币符号":"Token symbol"}<input value={form.tokenSymbol} onChange={e=>update("tokenSymbol",e.target.value)} required/></label><label>{zh?"代币合约":"Token contract"}<input value={form.tokenContract} onChange={e=>update("tokenContract",e.target.value)} placeholder="0x…" required/></label><label>{zh?"代币小数位":"Token decimals"}<input inputMode="numeric" value={form.tokenDecimals} onChange={e=>update("tokenDecimals",e.target.value)} required/></label><label>{zh?"收款钱包":"Receiver wallet"}<input value={form.receiverWallet} onChange={e=>update("receiverWallet",e.target.value)} placeholder="0x…" required/></label><label>{zh?"月付代币数量（现有月付价）":"Monthly token amount (existing monthly price)"}<input value={form.monthlyTokenAmount} onChange={e=>update("monthlyTokenAmount",e.target.value)} required/></label><label>{zh?"年付代币数量（现有年付价）":"Annual token amount (existing annual price)"}<input value={form.annualTokenAmount} onChange={e=>update("annualTokenAmount",e.target.value)} required/></label><label>{zh?"最少确认数":"Minimum confirmations"}<input inputMode="numeric" value={form.minConfirmations} onChange={e=>update("minConfirmations",e.target.value)} required/></label><label>{zh?"WalletConnect 项目标识":"WalletConnect Project ID"}<input value={form.walletConnectProjectId} onChange={e=>update("walletConnectProjectId",e.target.value)} placeholder={zh?"GreatLoveMeta.com 独立的 32 位 ID":"GreatLoveMeta-specific 32-character ID"}/></label><label className="admin-toggle"><input type="checkbox" checked={form.enabled} onChange={e=>update("enabled",e.target.checked)}/>{zh?"启用此通道":"Enable this rail"}</label><div className="admin-row-actions"><button disabled={busy}>{form.id?(zh?"保存修改":"Save changes"):(zh?"新增通道":"Add rail")}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)}>{zh?"取消":"Cancel"}</button>}</div></form>
    <div className="admin-setting-list">{settings.map(item=><article key={item.id}><h3>{item.label}</h3><p>{item.chainName} · {item.tokenSymbol} · Chain {item.chainId}</p><p>{item.monthlyTokenAmount} / {item.annualTokenAmount} {item.tokenSymbol}</p><div className="admin-row-actions"><button onClick={()=>edit(item)}>{zh?"编辑":"Edit"}</button><button className="danger" onClick={()=>void remove(item.id)} disabled={busy}>{zh?"停用":"Disable"}</button></div></article>)}</div>{message&&<p role="status">{message}</p>}
  </section>;
}
