"use client";

import { useEffect, useState } from "react";
import type { CryptoPaymentSetting } from "../lib/crypto-contract";
import type { SubscriptionPlan } from "../lib/subscription-plans";
import type { SiteLanguage } from "../lib/site-locale";

const empty = { id:"", label:"", chainName:"", chainId:"137", tokenSymbol:"USDC", tokenContract:"", tokenDecimals:"6", receiverWallet:"", monthlyTokenAmount:"", annualTokenAmount:"", minConfirmations:"12", walletConnectProjectId:"", enabled:true };

export function AdminCryptoSettings({ lang }: { lang: SiteLanguage }) {
  const zh = lang === "zh";
  const [settings, setSettings] = useState<CryptoPaymentSetting[]>([]);
  const [plans, setPlans] = useState<SubscriptionPlan[]>([]);
  const [form, setForm] = useState(empty);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  async function load() { const response=await fetch("/api/admin/crypto-settings",{cache:"no-store"}); const data=await response.json(); if(!response.ok)throw new Error(data.error); setSettings(data.settings||[]); setPlans(data.plans||[]); }
  useEffect(()=>{let active=true;fetch("/api/admin/crypto-settings",{cache:"no-store"}).then(async response=>{const data=await response.json();if(!response.ok)throw new Error(data.error);if(active){setSettings(data.settings||[]);setPlans(data.plans||[]);}}).catch(()=>{if(active)setMessage(zh?"无法读取本站收款通道。":"Unable to load site-local payment rails.");});return()=>{active=false};},[zh]);
  const update=(key:keyof typeof empty,value:string|boolean)=>setForm(current=>({...current,[key]:value}));
  function edit(item:CryptoPaymentSetting){setForm({id:item.id,label:item.label,chainName:item.chainName,chainId:String(item.chainId),tokenSymbol:item.tokenSymbol,tokenContract:item.tokenContract,tokenDecimals:String(item.tokenDecimals),receiverWallet:item.receiverWallet,monthlyTokenAmount:item.monthlyTokenAmount,annualTokenAmount:item.annualTokenAmount,minConfirmations:String(item.minConfirmations),walletConnectProjectId:item.walletConnectProjectId||"",enabled:Boolean(item.enabled)});}
  async function save(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage("");const response=await fetch("/api/admin/crypto-settings",{method:form.id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const data=await response.json().catch(()=>({}));if(response.ok){setForm(empty);await load();setMessage(zh?"本站加密收款通道已保存。":"Site-local crypto payment rail saved.");}else setMessage(data.error||(zh?"保存失败。":"Save failed."));setBusy(false);}
  async function remove(id:string){setBusy(true);const response=await fetch("/api/admin/crypto-settings",{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({id})});if(response.ok){await load();setMessage(zh?"通道已停用并保留审计记录。":"Rail disabled with audit history preserved.");}else setMessage(zh?"无法停用通道。":"Unable to disable rail.");setBusy(false);}
  const fields = [["label",zh?"显示名称":"Label"],["chainName",zh?"链名称":"Chain name"],["chainId","Chain ID"],["tokenSymbol",zh?"代币符号":"Token symbol"],["tokenContract",zh?"代币合约":"Token contract"],["tokenDecimals",zh?"代币小数位":"Token decimals"],["receiverWallet",zh?"收款钱包":"Receiver wallet"],["monthlyTokenAmount",zh?"月付代币数量":"Monthly token amount"],["annualTokenAmount",zh?"年付代币数量":"Annual token amount"],["minConfirmations",zh?"最少确认数":"Minimum confirmations"],["walletConnectProjectId","WalletConnect Project ID"]] as const;
  return <section className="admin-crypto"><div><p className="section-kicker">CRYPTO PAYMENT</p><h2>{zh?"GreatLoveMeta.com 独立加密支付配置":"GreatLoveMeta.com site-local crypto payment configuration"}</h2><p>{zh?"价格读取本站月度与年度套餐；链、ERC-20、收款钱包和 WalletConnect 项目标识仅属于本站。":"Prices come from this site's monthly and annual plans. Chain, ERC-20, receiver, and WalletConnect Project ID remain site-local."}</p><div className="admin-price-source">{plans.map(plan=><span key={plan.id}>{plan.id}: ${plan.price}</span>)}</div></div><form onSubmit={save}>{fields.map(([key,label])=><label key={key}>{label}<input value={String(form[key])} onChange={event=>update(key,event.target.value)} placeholder={key.includes("Contract")||key.includes("Wallet")?"0x…":key==="walletConnectProjectId"?(zh?"本站独立 32 位 ID":"Site-specific 32-character ID"):""} required={key!=="walletConnectProjectId"}/></label>)}<label className="admin-toggle"><input type="checkbox" checked={form.enabled} onChange={event=>update("enabled",event.target.checked)}/>{zh?"启用此通道":"Enable this rail"}</label><div className="admin-row-actions"><button disabled={busy}>{form.id?(zh?"保存修改":"Save changes"):(zh?"新增通道":"Add rail")}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)}>{zh?"取消":"Cancel"}</button>}</div></form><div className="admin-setting-list">{settings.map(item=><article key={item.id}><h3>{item.label}</h3><p>{item.chainName} · {item.tokenSymbol} · Chain {item.chainId}</p><p>{item.monthlyTokenAmount} / {item.annualTokenAmount} {item.tokenSymbol}</p><div className="admin-row-actions"><button onClick={()=>edit(item)}>{zh?"编辑":"Edit"}</button><button className="danger" onClick={()=>void remove(item.id)} disabled={busy}>{zh?"停用":"Disable"}</button></div></article>)}</div>{message&&<p role="status">{message}</p>}</section>;
}
