"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { CryptoPaymentSetting, CryptoPlanId } from "@/lib/crypto-contract";
import { explorerUrl } from "@/lib/crypto-contract";
import { SUBSCRIPTION_PLANS } from "@/lib/subscription-plans";

type Provider={request(args:{method:string;params?:unknown[]}):Promise<unknown>};type WalletChain={name:string;chainId:number;chainIdHex:string;nativeCurrency:{name:string;symbol:string;decimals:number};rpcUrls:string[];blockExplorerUrls:string[]};type WalletConnector={connect(config:unknown,market:{chain:WalletChain}):Promise<{provider:Provider;address:string}>;disconnect():Promise<void>};declare global{interface Window{GreatLoveAutoSwapOnboard?:WalletConnector}}
type Payment={txHash:string;chainName:string;tokenSymbol:string;planId:string;status:string;entitlementStatus:string;createdAt:string};
type Status={signedIn:boolean;wallet?:string|null;cryptoSettings?:CryptoPaymentSetting[];payments?:Payment[]};
const plans=SUBSCRIPTION_PLANS;
const chainMeta:Record<number,Omit<WalletChain,"chainId"|"chainIdHex">>={1:{name:"Ethereum",nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:["https://ethereum-rpc.publicnode.com"],blockExplorerUrls:["https://etherscan.io"]},56:{name:"BNB Smart Chain",nativeCurrency:{name:"BNB",symbol:"BNB",decimals:18},rpcUrls:["https://bsc-rpc.publicnode.com"],blockExplorerUrls:["https://bscscan.com"]},137:{name:"Polygon",nativeCurrency:{name:"POL",symbol:"POL",decimals:18},rpcUrls:["https://polygon-bor-rpc.publicnode.com"],blockExplorerUrls:["https://polygonscan.com"]},8453:{name:"Base",nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:["https://base-rpc.publicnode.com"],blockExplorerUrls:["https://basescan.org"]}};const walletChain=(setting:CryptoPaymentSetting):WalletChain=>{const details=chainMeta[setting.chainId];return{...(details||{name:setting.chainName,nativeCurrency:{name:"Ether",symbol:"ETH",decimals:18},rpcUrls:[],blockExplorerUrls:[]}),chainId:setting.chainId,chainIdHex:`0x${setting.chainId.toString(16)}`}};async function loadWalletConnector():Promise<WalletConnector>{if(window.GreatLoveAutoSwapOnboard)return window.GreatLoveAutoSwapOnboard;await new Promise<void>((resolve,reject)=>{const existing=document.getElementById("site-wallet-connector")as HTMLScriptElement|null;if(existing){existing.addEventListener("load",()=>resolve(),{once:true});existing.addEventListener("error",()=>reject(new Error("WALLET_CONNECTOR_UNAVAILABLE")),{once:true});return;}const script=document.createElement("script");script.id="site-wallet-connector";script.src="/wallet-assets/greatlove-onboard.js";script.async=true;script.addEventListener("load",()=>resolve(),{once:true});script.addEventListener("error",()=>reject(new Error("WALLET_CONNECTOR_UNAVAILABLE")),{once:true});document.body.appendChild(script);});if(!window.GreatLoveAutoSwapOnboard)throw new Error("WALLET_CONNECTOR_UNAVAILABLE");return window.GreatLoveAutoSwapOnboard;}const amountFor=(setting:CryptoPaymentSetting,plan:CryptoPlanId)=>plan==="monthly"?setting.monthlyTokenAmount:setting.annualTokenAmount;
function atomic(value:string,decimals:number){const[whole,fraction=""]=value.split(".");return BigInt(`${whole||"0"}${fraction.padEnd(decimals,"0").slice(0,decimals)}`);}

export default function CryptoCheckout({initialPlan,language}:{initialPlan:CryptoPlanId;language:"zh"|"en"}){const zh=language==="zh";const[status,setStatus]=useState<Status>({signedIn:false});const[step,setStep]=useState(1);const[plan,setPlan]=useState<CryptoPlanId>(initialPlan);const[settingId,setSettingId]=useState("");const[wallet,setWallet]=useState("");const[walletProvider,setWalletProvider]=useState<Provider|null>(null);const[connected,setConnected]=useState(false);const[direct,setDirect]=useState(false);const[balance,setBalance]=useState("");const[txHash,setTxHash]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState("");
  async function load(){const response=await fetch("/api/billing/status",{cache:"no-store"});const data=await response.json();setStatus(data);setWallet(data.wallet||"");}
  useEffect(()=>{let active=true;fetch("/api/billing/status",{cache:"no-store"}).then(response=>response.json()).then(data=>{if(active){setStatus(data);setWallet(data.wallet||"");}}).catch(()=>{if(active)setMessage(zh?"暂时无法读取结账配置。":"Unable to load checkout settings.");});return()=>{active=false;};},[zh]);
  const settings=status.cryptoSettings||[];const selected=settings.find(item=>item.id===(settingId||settings[0]?.id));const selectedPlan=plans.find(item=>item.id===plan)!;const displayPrice=(planId:CryptoPlanId)=>{const rail=settings[0],cents=rail?(planId==="monthly"?rail.monthlyAmountCents:rail.annualAmountCents):0;return cents?new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(cents/100):(plans.find(item=>item.id===planId)?.fallbackPrice||"");};
  function requireLogin(){if(status.signedIn)return true;window.location.assign(`/${language}/auth/login?returnTo=${encodeURIComponent(`/${language}/pricing/crypto?plan=${plan}`)}`);return false;}
  async function saveWallet(value:string){const normalized=value.trim().toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(normalized))throw new Error("INVALID_WALLET");const response=await fetch("/api/billing/crypto/wallet",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({wallet:normalized})});if(!response.ok)throw new Error("SAVE_FAILED");setWallet(normalized);await load();}
  async function connectWallet(){if(!selected||!requireLogin())return;try{setBusy("connect");setMessage("");const connector=await loadWalletConnector(),result=await connector.connect({walletMethods:{walletconnect:{enabled:true,projectId:"0d850a98123d379c16d0d9f2555d39bb",version:2,requiredChains:[selected.chainId],dappUrl:window.location.origin}},walletConnectApp:{appName:"GreatLoveMeta.com",description:"GreatLoveMeta.com subscription checkout",icon:"<svg></svg>",logo:"<svg></svg>"}},{chain:walletChain(selected)}),address=String(result.address||"");if(!/^0x[a-fA-F0-9]{40}$/.test(address))throw new Error("INVALID_WALLET");await saveWallet(address);setWalletProvider(result.provider);setWallet(address);setConnected(true);setDirect(false);setMessage(zh?"钱包已连接，请确认发送付款交易。":"Wallet connected. Confirm the payment transaction.");}catch{setMessage(zh?"无法连接钱包；请扫描二维码、在钱包中允许 GreatLoveMeta.com 连接，或改用直接转账。":"Could not connect the wallet. Scan the QR code, approve GreatLoveMeta.com in your wallet, or use direct transfer.");}finally{setBusy("");}}
  async function sendPayment(){if(!selected||!wallet)return;const provider=walletProvider||(window as unknown as{ethereum?:Provider}).ethereum;if(!provider){setMessage(zh?"未检测到已连接的钱包。":"No connected wallet was detected.");return;}try{setBusy("send");const value=amountFor(selected,plan);const data=`0xa9059cbb${selected.receiverWallet.slice(2).padStart(64,"0")}${atomic(value,selected.tokenDecimals).toString(16).padStart(64,"0")}`;const hash=await provider.request({method:"eth_sendTransaction",params:[{from:wallet,to:selected.tokenContract,data}]});if(typeof hash!=="string")throw new Error("NO_HASH");setTxHash(hash);await verify(hash);}catch{setMessage(zh?"交易未发送；请检查钱包确认、网络和余额。":"Transaction was not sent. Check wallet confirmation, network, and balance.");}finally{setBusy("");}}
  async function refreshBalance(){if(!selected)return;setBusy("balance");const response=await fetch("/api/billing/crypto/balance",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({settingId:selected.id})});const data=await response.json().catch(()=>({}));if(response.ok)setBalance(`${data.amount} ${data.symbol}`);else setMessage(data.error||(zh?"无法读取余额。":"Unable to read balance."));setBusy("");}
  async function verify(hashValue=txHash){if(!selected||!wallet)return;setBusy("verify");let hash=hashValue.trim().toLowerCase();if(!/^0x[a-f0-9]{64}$/.test(hash)){const lookup=await fetch("/api/billing/crypto/find-payment",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan,settingId:selected.id})});const found=await lookup.json().catch(()=>({}));if(!lookup.ok||!found.txHash){setMessage(found.error||(zh?"尚未找到匹配的近期付款。":"No matching recent payment was found."));setBusy("");return;}hash=found.txHash;setTxHash(hash);}const response=await fetch("/api/billing/crypto/verify",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({plan,settingId:selected.id,txHash:hash})});const data=await response.json().catch(()=>({}));setMessage(data.verified?(zh?"付款已由服务端完成链上验证；Clerk 权益同步进入待处理状态。":"Payment verified on-chain by the server; Clerk entitlement synchronization is pending."):(data.error||(zh?"付款验证失败。":"Payment verification failed.")));if(data.verified)await load();setBusy("");}
  async function saveDirect(){try{setBusy("wallet");await saveWallet(wallet);setMessage(zh?"付款钱包已保存，可刷新余额或查询近期付款。":"Payer wallet saved. You can refresh balance or find a recent payment.");}catch{setMessage(zh?"请输入有效的 EVM 钱包地址。":"Enter a valid EVM wallet address.");}finally{setBusy("");}}
  return <section className="crypto-flow"><Link href={`/${language}/pricing`}>← {zh?"返回订阅方案":"Back to plans"}</Link><header><p className="eyebrow jade">CRYPTO CHECKOUT</p><h1>{zh?"使用加密货币订阅 GreatLoveMeta.com":"Subscribe to GreatLoveMeta.com with crypto"}</h1><p>{zh?"三步完成套餐、链与钱包选择。我们绝不会要求私钥或助记词。":"Choose a plan, rail, and wallet in three steps. We never request a private key or seed phrase."}</p></header><ol className="payment-steps"><li className={step>=1?"active":""}>1. {zh?"套餐":"Plan"}</li><li className={step>=2?"active":""}>2. {zh?"链与代币":"Chain & token"}</li><li className={step>=3?"active":""}>3. {zh?"钱包与验证":"Wallet & verify"}</li></ol>
    {step===1&&<section className="crypto-card"><h2>{zh?"步骤 1：选择订阅套餐":"Step 1: Choose a subscription plan"}</h2><div className="crypto-options">{plans.map(item=><label key={item.id}><input type="radio" checked={plan===item.id} onChange={()=>setPlan(item.id)}/><span><strong>{displayPrice(item.id)}</strong><small>{zh?`${item.months} 个月`:`${item.months} month${item.months>1?"s":""}`}</small></span></label>)}</div><ul><li>{zh?"内置专属小组音视频与沟通中心":"Private group audio/video and communication center"}</li><li>{zh?"公开网络研讨会与 HLS 广播":"Open webinars and HLS broadcasting"}</li><li>{zh?"DeepSeek V4 Flash 默认，可选 OpenAI":"DeepSeek V4 Flash by default, OpenAI optional"}</li></ul><button onClick={()=>setStep(2)}>{zh?"下一步：选择链":"Next: choose chain"} →</button></section>}
    {step===2&&<section className="crypto-card"><button className="text-button" onClick={()=>setStep(1)}>← {zh?"上一步":"Back"}</button><h2>{zh?"步骤 2：选择管理员启用的链与 ERC-20":"Step 2: Choose an administrator-enabled chain and ERC-20"}</h2>{settings.length?<div className="crypto-options">{settings.map(item=><label key={item.id}><input type="radio" checked={(settingId||settings[0]?.id)===item.id} onChange={()=>setSettingId(item.id)}/><span><strong>{item.label}</strong><small>{item.chainName} · {amountFor(item,plan)} {item.tokenSymbol}</small></span></label>)}</div>:<p>{zh?"管理员尚未启用 GreatLoveMeta.com 独立收款通道。":"No GreatLoveMeta-specific payment rail is enabled yet."}</p>}<button disabled={!settings.length} onClick={()=>{if(requireLogin())setStep(3);}}>{zh?"下一步：付款钱包":"Next: payment wallet"} →</button></section>}
    {step===3&&selected&&<section className="crypto-card"><button className="text-button" onClick={()=>setStep(2)}>← {zh?"上一步":"Back"}</button><h2>{zh?"步骤 3：连接钱包或直接转账":"Step 3: Connect a wallet or transfer directly"}</h2><div className="payment-summary"><strong>{displayPrice(selectedPlan.id)} · {zh?`${selectedPlan.months} 个月`:`${selectedPlan.months} month${selectedPlan.months>1?"s":""}`}</strong><span>{amountFor(selected,plan)} {selected.tokenSymbol} · {selected.chainName}</span></div><dl><div><dt>{zh?"收款钱包":"Receiver"}</dt><dd>{explorerUrl(selected.chainId,"address",selected.receiverWallet)?<a href={explorerUrl(selected.chainId,"address",selected.receiverWallet)!} target="_blank" rel="noreferrer">{selected.receiverWallet}</a>:selected.receiverWallet}</dd></div><div><dt>{zh?"代币合约":"Token contract"}</dt><dd>{explorerUrl(selected.chainId,"token",selected.tokenContract)?<a href={explorerUrl(selected.chainId,"token",selected.tokenContract)!} target="_blank" rel="noreferrer">{selected.tokenContract}</a>:selected.tokenContract}</dd></div></dl>{!direct?<>{connected?<div className="direct-payment"><p>{zh?`已连接 ${wallet}`:`Connected ${wallet}`}</p><button onClick={()=>void sendPayment()} disabled={busy==="send"}>{busy==="send"?"…":(zh?`发送 ${amountFor(selected,plan)} ${selected.tokenSymbol}`:`Send ${amountFor(selected,plan)} ${selected.tokenSymbol}`)}</button></div>:<button onClick={()=>void connectWallet()} disabled={busy==="connect"}>{busy==="connect"?"…":(zh?"连接钱包":"Connect wallet")}</button>}<button className="text-button" onClick={()=>setDirect(true)}>{zh?"改用直接转账":"Use direct transfer fallback"} →</button></>:<div className="direct-payment"><label>{zh?"付款钱包":"Payer wallet"}<input value={wallet} onChange={e=>setWallet(e.target.value)} placeholder="0x…"/></label><button onClick={()=>void saveDirect()} disabled={busy==="wallet"}>{zh?"保存付款钱包":"Save payer wallet"}</button><p>{balance||(zh?"尚未读取余额":"Balance not loaded")} <button className="inline" onClick={()=>void refreshBalance()} disabled={busy==="balance"}>{zh?"刷新余额":"Refresh balance"}</button></p><label>{zh?"交易哈希（可选）":"Transaction hash (optional)"}<input value={txHash} onChange={e=>setTxHash(e.target.value)} placeholder="0x…"/><small>{zh?"留空将按付款钱包、收款钱包、代币和金额查询近期记录。":"Leave blank to search recent activity by payer, receiver, token, and amount."}</small></label><button onClick={()=>void verify()} disabled={!wallet||busy==="verify"}>{busy==="verify"?"…":(zh?"查询并验证付款":"Find and verify payment")}</button></div>}{message&&<p role="status" className="billing-message">{message}</p>}</section>}
    {status.signedIn&&<section className="crypto-card payment-history"><h2>{zh?"付款记录":"Payment history"}</h2>{status.payments?.length?status.payments.map(item=><article key={item.txHash}><div><strong>{item.planId} · {item.tokenSymbol}</strong><small>{item.chainName} · {item.createdAt}</small></div><a href={explorerUrl(selected?.chainId||0,"tx",item.txHash)||"#"} target="_blank" rel="noreferrer">{item.txHash}</a><span>{item.status} · {item.entitlementStatus}</span></article>):<p>{zh?"暂无链上付款记录。":"No on-chain payments yet."}</p>}</section>}
  </section>;
}
