import { SiteFooter } from "./SiteFooter";
import { SiteHeader } from "./SiteHeader";
type PageKind = "about" | "privacy" | "terms";
const copy = {
  about: {
    en: { eyebrow: "ABOUT GREATLOVEMETA.DIGITAL", title: "A trusted digital home for people who think and act globally.", intro: "GreatLoveMeta.com is a bilingual platform for identity, informed participation, community connection, and transparent citizen-led projects.", sections: [["Our direction", "Bring digital identity, global news, events, conversations, collaboration, and project outcomes into one coherent civic experience."], ["Community principles", "Respect people across cultures, distinguish fact from opinion, protect privacy, reject harassment, and make collaboration transparent."], ["Two-domain ecosystem", "GreatLoveMeta.com is the trusted main platform. cz.cool is the lighter youth-facing entry for interactive identity experiences and social campaigns."]] },
    zh: { eyebrow: "关于 GREATLOVEMETA.DIGITAL", title: "为拥有全球视野并愿意行动的人建立可信数字家园。", intro: "GreatLoveMeta.com 是连接数字身份、知识参与、全球社区与透明公民项目的中英文平台。", sections: [["我们的方向", "将数字身份、全球新闻、活动、交流、协作与项目成果整合为一致的公民体验。"], ["社区原则", "尊重不同文化，区分事实与观点，保护隐私，反对骚扰，并让合作过程保持透明。"], ["双域名生态", "GreatLoveMeta.com 是可信主平台；cz.cool 是面向年轻人的轻量入口，用于互动身份体验与社交活动。"]] },
  },
  privacy: {
    en: { eyebrow: "PRIVACY POLICY", title: "Clear choices for your identity and data.", intro: "Effective July 22, 2026. This notice applies to GreatLoveMeta.com and identity-linked experiences initiated from cz.cool.", sections: [["Information we process", "Account email, display name, profile settings, language and reading preferences, community content, project participation, messages, live-chat data, and files you choose to upload."], ["How it is used", "To authenticate you, maintain your profile, deliver community and messaging features, protect the platform, and improve the experience."], ["Service providers", "Clerk supports authentication. OpenAI processes only the content you deliberately submit to Guru features. Hosting, database, and object-storage providers process data required to operate the service."], ["Wallets and credentials", "Wallet binding is optional. A wallet is linked only after an explicit signature challenge; we do not request or store private keys or seed phrases."], ["Your choices", "You can update profile preferences and request access, correction, export, or deletion of eligible account data through the published contact process."]] },
    zh: { eyebrow: "隐私政策", title: "清楚掌握您的身份与资料。", intro: "生效日期：2026 年 7 月 22 日。本说明适用于 GreatLoveMeta.com 以及从 cz.cool 发起并连接同一身份的体验。", sections: [["我们处理的资料", "账户邮箱、显示名称、个人档案设置、语言与阅读偏好、社区内容、项目参与、消息、Live Chat 资料以及您主动上传的文件。"], ["资料用途", "用于身份验证、维护个人档案、提供社区与消息功能、保护平台安全并改进体验。"], ["服务提供方", "Clerk 支持身份验证；只有当您主动使用 Guru 功能时，必要内容才会发送给 OpenAI；托管、数据库与对象存储服务处理运行平台所需资料。"], ["钱包与凭证", "钱包绑定完全可选，并且只在明确签名验证后连接；我们不会要求或保存私钥与助记词。"], ["您的选择", "您可更新个人档案偏好，并通过公布的联系流程申请访问、更正、导出或删除符合条件的账户资料。"]] },
  },
  terms: {
    en: { eyebrow: "TERMS OF USE", title: "Participate safely and constructively.", intro: "Effective July 22, 2026. By using the platform, you agree to these service and community terms.", sections: [["Platform service", "Features may evolve or temporarily pause. News summaries, Guru responses, identity types, and community content are informational and do not create legal citizenship, government status, or guaranteed rights."], ["Accounts and conduct", "Protect your account, respect other members, and do not harass, impersonate, publish unlawful material, manipulate platform systems, or interfere with another person’s access."], ["User content", "You retain rights in content you submit and grant the platform the limited permission needed to store, display, transmit, moderate, and operate that content within the service."], ["Projects and events", "Project owners and event organizers are responsible for their stated terms, eligibility, safety, finances, and outcomes. Verify material commitments before participating."], ["Digital assets", "No page or AI response constitutes investment, legal, tax, or financial advice. Optional wallet and credential functions must never require disclosure of private keys or seed phrases."]] },
    zh: { eyebrow: "使用条款", title: "安全、友善、建设性地参与。", intro: "生效日期：2026 年 7 月 22 日。使用本平台即表示您同意以下服务与社区条款。", sections: [["平台服务", "功能可能持续调整或暂时中断。新闻摘要、Guru 回答、身份类型和社区内容仅供参考，不构成法律公民身份、政府身份或权利保证。"], ["账户与行为", "请保护账户、尊重其他会员，不得骚扰、冒充、发布违法资料、操纵平台系统或干扰他人使用。"], ["用户内容", "您保留所提交内容的权利，并授权平台在提供服务所需范围内存储、展示、传输、管理该内容。"], ["项目与活动", "项目方与活动主办方对其规则、资格、安全、资金与成果负责；在作出重要承诺前请自行核实。"], ["数字资产", "任何页面或 AI 回答均不构成投资、法律、税务或财务意见。可选的钱包与凭证功能绝不会要求披露私钥或助记词。"]] },
  },
} as const;
export function LegalPage({ lang, kind }: { lang: "en" | "zh"; kind: PageKind }) { const page = copy[kind][lang]; return <main className="legal-page"><SiteHeader lang={lang}/><article className="legal-main"><p className="section-kicker">{page.eyebrow}</p><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p><div className="legal-sections">{page.sections.map(([title,body])=><section key={title}><h2>{title}</h2><p>{body}</p></section>)}</div></article><SiteFooter lang={lang}/></main>; }
