"use client";

import { useEffect, useState } from "react";
import { ReferralMediaDrawer } from "./ReferralMediaDrawer";

type ReferredMember = { id: string; referralId: string; displayName: string; status: string; joinedAt: number; memberSince: number };
type Data = { subscription: { status: string; cadence: string } | null; referral: { code: string; url: string; pending: number; qualified: number; needsReferral: boolean; joined: ReferredMember[] }; points: number; rewardHistory: Array<{ id: string; points: number; reason: string; createdAt: number }>; notifications: { language: string; marketingEmail: boolean; productEmail: boolean; reminderEmail: boolean } };

function DashboardIcon({ name }: { name: "copy" | "share" | "media" | "history" | "users" }) {
  if (name === "copy") return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V6a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2"/></svg>;
  if (name === "share") return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="m8.2 10.8 7.6-4.5M8.2 13.2l7.6 4.5"/></svg>;
  if (name === "media") return <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="8.5" cy="9" r="1.5"/><path d="m4.5 17 5-5 3.5 3 2.5-2.5 4 4"/></svg>;
  if (name === "history") return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7v5h5"/><path d="M5.4 17a8 8 0 1 0-.9-8"/><path d="M12 7v5l3 2"/></svg>;
  return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9.5 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z"/><path d="M3 20c.5-4 2.7-6 6.5-6s6 2 6.5 6"/><path d="M17 11a3 3 0 1 0 0-6M17 14c2.4.3 3.8 1.8 4 4.5"/></svg>;
}

export function MembershipPanel({ lang }: { lang: "en" | "zh" }) {
  const [data, setData] = useState<Data | null>(null);
  const [message, setMessage] = useState("");
  const [showReferralDetails, setShowReferralDetails] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [referralInput, setReferralInput] = useState("");
  const [mediaMode, setMediaMode] = useState<"share" | null>(null);
  const [selectedMember, setSelectedMember] = useState<ReferredMember | null>(null);
  const [tipMessage, setTipMessage] = useState("");
  const [unreadMessages, setUnreadMessages] = useState(0);
  useEffect(() => { fetch("/api/platform").then(response => response.json()).then(setData).catch(() => undefined); }, []);
  useEffect(() => { let active = true; const refresh = () => fetch("/api/messages?summary=1").then(response => response.ok ? response.json() : null).then(result => { if (active && result) setUnreadMessages(Number(result.unread) || 0); }).catch(() => undefined); refresh(); const timer = window.setInterval(refresh, 30000); return () => { active = false; window.clearInterval(timer); }; }, []);
  if (!data) return <section className="member-panel">{lang === "zh" ? "正在准备会员中心…" : "Preparing membership…"}</section>;
  async function copy() { await navigator.clipboard.writeText(data!.referral.url); setMessage(lang === "zh" ? "已复制" : "Copied"); setTimeout(() => setMessage(""), 1600); }
  async function share() { const item = { title: lang === "zh" ? "大爱元宇宙" : "GreatLoveMeta.com", text: lang === "zh" ? "和我一起加入大爱元宇宙。填写推荐码后双方各得 100 积分，首个付费周期另享 15% 优惠。" : "Join me on GreatLoveMeta.com. We each earn 100 points when you add my code, plus 15% off your first paid period.", url: data!.referral.url }; if (navigator.share) { try { await navigator.share(item); } catch { return; } } else { await copy(); } }
  async function claim(event: React.FormEvent) { event.preventDefault(); const response = await fetch("/api/platform", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "claim_referral", referralCode: referralInput }) }); const result = await response.json().catch(() => ({})); if (!response.ok) { setMessage(label ? ({ self: "不能填写自己的推荐码", assigned: "介绍人已经记录，不能更换", invalid: "推荐码无效" }[result.reason as string] || "推荐码无法使用") : ({ self: "You cannot use your own code", assigned: "Your introducer is already recorded", invalid: "Invalid referral code" }[result.reason as string] || "The code could not be used")); return; } const updated = await fetch("/api/platform").then(value => value.json()); setData(updated); setReferralInput(""); setMessage(label ? "双方各获得 100 积分" : "You both received 100 points"); }
  async function save() { await fetch("/api/platform", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(data!.notifications) }); setMessage(lang === "zh" ? "已保存" : "Saved"); setTimeout(() => setMessage(""), 1600); }
  async function tip(points: number) { if (!selectedMember) return; const response = await fetch("/api/platform", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "tip", recipientId: selectedMember.id, points }) }); const result = await response.json().catch(() => ({})); setTipMessage(response.ok ? (lang === "zh" ? `已赠送 ${points} 积分。` : `${points} points sent.`) : result.error === "insufficient" ? (lang === "zh" ? "积分余额不足。" : "Not enough points.") : (lang === "zh" ? "暂时无法赠送积分。" : "The points could not be sent.")); if (response.ok) setData({ ...data!, points: data!.points - points }); }
  const label = lang === "zh";
  return <><section className="dashboard-summary"><span><b>{label ? "已加入" : "Active"}</b><small>{label ? "公民身份" : "Citizen status"}</small></span><button onClick={() => setShowHistory(true)}><b>{data.points}</b><small>{label ? "Guru 积分 · 记录" : "Guru points · History"}</small></button><span><b>{data.referral.pending + data.referral.qualified}</b><small>{label ? "社区推荐" : "Citizen referrals"}</small></span><a href={`/${lang}/messages`} aria-label={label ? `${unreadMessages} 条未读消息，打开消息中心` : `${unreadMessages} unread messages, open Messages`}><b>{unreadMessages > 99 ? "99+" : unreadMessages}</b><small>{label ? "未读消息 · 打开" : "Unread messages · Open"}</small></a></section><section className="member-panel">{data.referral.needsReferral && <div className="referral-claim"><div><p className="section-kicker">{label ? "有朋友邀请你吗？" : "WERE YOU INVITED?"}</p><h2>{label ? "填写推荐码，双方各得 100 积分。" : "Add the referral code. You both earn 100 points."}</h2><p>{label ? "介绍人只能设置一次，不能填写自己的推荐码。" : "An introducer can be set only once, and you cannot use your own code."}</p></div><form onSubmit={claim}><input required maxLength={6} value={referralInput} onChange={event => setReferralInput(event.target.value.toUpperCase())} placeholder={label ? "输入 6 位推荐码" : "Enter 6-character code"}/><button disabled={referralInput.trim().length !== 6}>{label ? "领取奖励" : "Claim rewards"} →</button></form></div>}<div className="member-heading"><div><p className="section-kicker">{label ? "会员与奖励" : "MEMBERSHIP & REWARDS"}</p><h2>{label ? "会员、推荐与积分" : "Membership, referrals & points"}</h2></div><a className="primary-button" href={`/${lang}/pricing`}>{label ? "查看会员方案" : "View plans"}</a></div><div className="member-grid">
    <article><small>{label ? "会员状态" : "Membership"}</small><strong>{data.subscription ? (label ? ({ trialing: "试用中", active: "有效", cancelled: "已取消", suspended: "已暂停", expired: "已到期", past_due: "付款逾期" }[data.subscription.status] ?? data.subscription.status) : data.subscription.status) : (label ? "免费" : "Free")}</strong><p>{data.subscription ? (label ? (data.subscription.cadence === "annual" ? "年度方案" : "月度方案") : data.subscription.cadence) : label ? "可开始 7 天免费试用" : "7-day free trial available"}</p></article>
    <article><small>{label ? "Guru 积分" : "Guru points"}</small><strong>{data.points}</strong><p>{label ? "可用于社区参与奖励与会员打赏。" : "Use points for participation rewards and community tips."}</p><button className="history-button" onClick={() => setShowHistory(value => !value)}>{label ? "查看积分记录" : "View reward history"} →</button>{showHistory && <div className="reward-history">{data.rewardHistory.length ? data.rewardHistory.map(item => <div key={item.id}><span>{label ? ({ referral_join: "填写推荐码", referral_invite: "成功邀请朋友", daily_training: "每日参与" }[item.reason] || item.reason) : ({ referral_join: "Referral joined", referral_invite: "Friend invited", daily_training: "Daily participation" }[item.reason] || item.reason)}<small>{new Date(item.createdAt * 1000).toLocaleDateString(label ? "zh-CN" : "en-US")}</small></span><b>{item.points > 0 ? "+" : ""}{item.points}</b></div>) : <p>{label ? "暂无积分记录" : "No reward activity yet"}</p>}</div>}</article>
    <article className="share-card"><small>{label ? "邀请朋友" : "Refer friends"}</small><strong>{data.referral.code}</strong><p>{label ? "朋友填写推荐码后，双方立即各得 100 积分；朋友首个付费周期另享 15% 优惠。" : "When a friend adds your code, you both receive 100 points immediately; they also get 15% off their first paid period."}</p><div className="share-url"><input readOnly value={data.referral.url}/></div><div className="dashboard-share-actions"><button onClick={copy} aria-label={label ? "复制邀请链接" : "Copy invite link"}><DashboardIcon name="copy"/><span>{message || (label ? "复制" : "Copy")}</span></button><button onClick={share} aria-label={label ? "分享邀请链接" : "Share referral link"}><DashboardIcon name="share"/><span>{label ? "分享" : "Share"}</span></button><button onClick={() => setMediaMode("share")} aria-label={label ? "分享图片或短片" : "Share image or clip"}><DashboardIcon name="media"/><span>{label ? "分享作品" : "Media"}</span></button><button onClick={() => setShowReferralDetails(true)} aria-label={label ? "查看推荐历史" : "View referral history"}><DashboardIcon name="history"/><span>{label ? "历史" : "History"}</span></button></div></article>
    <article className="email-card"><small>{label ? "邮件偏好" : "Email preferences"}</small><label><input type="checkbox" checked={data.notifications.productEmail} onChange={event => setData({ ...data, notifications: { ...data.notifications, productEmail: event.target.checked } })}/>{label ? "产品与账户通知" : "Product and account"}</label><label><input type="checkbox" checked={data.notifications.reminderEmail} onChange={event => setData({ ...data, notifications: { ...data.notifications, reminderEmail: event.target.checked } })}/>{label ? "项目与活动提醒" : "Project and event reminders"}</label><label><input type="checkbox" checked={data.notifications.marketingEmail} onChange={event => setData({ ...data, notifications: { ...data.notifications, marketingEmail: event.target.checked } })}/>{label ? "新闻与会员资讯" : "News and member updates"}</label><button onClick={save}>{message || (label ? "保存偏好" : "Save preferences")}</button></article>
  </div></section><ReferralMediaDrawer open={mediaMode !== null} onClose={() => setMediaMode(null)} lang={lang} referralUrl={data.referral.url} referralCode={data.referral.code}/><button className="dashboard-referral-fab" onClick={() => setShowReferralDetails(true)} aria-label={label ? "查看推荐详情" : "View referral details"} aria-expanded={showReferralDetails}><DashboardIcon name="users"/><span><b>{data.referral.pending + data.referral.qualified}</b>{label ? "推荐" : "Referrals"}</span></button>{showReferralDetails && <div className="dashboard-referral-backdrop" onMouseDown={() => setShowReferralDetails(false)}><section className="dashboard-referral-drawer" onMouseDown={event => event.stopPropagation()}><button className="dashboard-drawer-close" onClick={() => setShowReferralDetails(false)} aria-label={label ? "关闭" : "Close"}>×</button><p className="section-kicker">{label ? "推荐详情" : "REFERRAL DETAILS"}</p><h2>{label ? "推荐记录" : "Referral history"}</h2><div className="referral-detail"><span><b>{data.referral.pending}</b>{label ? "待完成" : "Pending"}</span><span><b>{data.referral.qualified}</b>{label ? "已奖励" : "Qualified"}</span></div>{data.referral.joined.length === 0 ? <p>{label ? "还没有推荐记录。分享专属链接后，第一位朋友会显示在这里。" : "No referrals yet. Share your personal link and your first friend will appear here."}</p> : <div className="referral-people">{data.referral.joined.map(item => <button type="button" key={item.id} onClick={() => { setSelectedMember(item); setTipMessage(""); }}><div><b>{item.displayName}</b><small>{new Date(item.joinedAt * 1000).toLocaleDateString(label ? "zh-CN" : "en-US")}</small></div><span>{item.status === "qualified" ? (label ? "已奖励" : "Rewarded") : (label ? "已加入 · 待付费确认" : "Joined · payment pending")}</span><i>→</i></button>)}</div>}</section></div>}{selectedMember && <div className="referral-member-backdrop" onMouseDown={() => setSelectedMember(null)}><section className="referral-member-profile" onMouseDown={event => event.stopPropagation()}><button className="dashboard-drawer-close" onClick={() => setSelectedMember(null)}>×</button><span className="referral-member-avatar">{selectedMember.displayName.slice(0,1).toUpperCase()}</span><h2>{selectedMember.displayName}</h2><p>{(label ? "会员加入于 " : "Member since ") + new Date(selectedMember.memberSince * 1000).toLocaleDateString(label ? "zh-CN" : "en-US")}</p><div className="referral-member-actions"><a href={"/" + lang + "/messages?member=" + encodeURIComponent(selectedMember.id)}>{label ? "发送消息" : "Send message"}</a><a href={"/" + lang + "/messages?member=" + encodeURIComponent(selectedMember.id)}>{label ? "开始实时聊天" : "Start Live Chat"}</a></div><div className="referral-tip-panel"><b>{label ? "赠送 Guru 积分" : "Send Guru points"}</b><p>{label ? "积分会立即转入对方账户。" : "Points transfer to this member immediately."}</p><div>{[10,25,50,100].map(points => <button key={points} onClick={() => tip(points)}>+{points}</button>)}</div>{tipMessage && <small>{tipMessage}</small>}</div></section></div>}</>;
}
