import type { SiteLanguage } from "./site-locale";

export type AuthInterfaceCopy = {
  title:string; description:string; quote:string; back:string; meta:string; eyebrow:string; continueText:string;
  email:string; password:string; createPassword:string; confirmPassword:string; code:string; spam:string;
  sendCode:string; usePassword:string; useCode:string; verify:string; createAndSignIn:string; continuePassword:string;
  anotherEmail:string; wait:string; completing:string;
};

const copies:Record<SiteLanguage,AuthInterfaceCopy>={
  en:{title:"Sign in or join",description:"Enter your email for a one-time code. Your first verified sign-in creates a GreatLoveMeta account automatically.",quote:"Great communities grow through participation, trust and shared progress.",back:"Back to home",meta:"GREATLOVE METAVERSE COMMUNITY",eyebrow:"SECURE ACCOUNT ACCESS",continueText:"Continue with an email code or password. A new verified email creates your account automatically.",email:"Email address",password:"Password",createPassword:"Create password",confirmPassword:"Confirm password",code:"One-time code",spam:"If you don't see the code email in your inbox, check your Spam or Junk folder.",sendCode:"Send secure code",usePassword:"Use password instead",useCode:"Use an email code instead",verify:"Verify & continue",createAndSignIn:"Create password & sign in",continuePassword:"Continue with password",anotherEmail:"Use another email",wait:"Please wait…",completing:"Completing secure sign-in…"},
  zh:{title:"登录或加入",description:"输入邮箱获取一次性验证码。首次验证成功后，系统将自动创建大爱元宇宙账号。",quote:"伟大的社区，成长于参与、信任与共同进步。",back:"返回首页",meta:"大爱元宇宙社区",eyebrow:"安全账户访问",continueText:"使用邮箱验证码或密码继续。首次验证邮箱会自动创建账户。",email:"电子邮箱",password:"密码",createPassword:"创建密码",confirmPassword:"确认密码",code:"一次性验证码",spam:"如果收件箱中没有看到验证码邮件，请检查垃圾邮件或广告邮件文件夹。",sendCode:"发送安全验证码",usePassword:"改用密码",useCode:"改用邮箱验证码",verify:"验证并继续",createAndSignIn:"设置密码并登录",continuePassword:"使用密码继续",anotherEmail:"更换邮箱",wait:"请稍候…",completing:"正在完成安全登录…"},
  ja:{title:"ログインまたは参加",description:"メールアドレスを入力してワンタイムコードを受け取ります。初回の確認済みログインでグレートラブメタのアカウントが自動作成されます。",quote:"すばらしいコミュニティは、参加、信頼、共に歩む進歩から育ちます。",back:"ホームに戻る",meta:"GREATLOVE メタバースコミュニティ",eyebrow:"安全なアカウントアクセス",continueText:"メールコードまたはパスワードで続行します。確認済みの新しいメールでアカウントが自動作成されます。",email:"メールアドレス",password:"パスワード",createPassword:"パスワードを作成",confirmPassword:"パスワードを確認",code:"ワンタイムコード",spam:"受信トレイにコードが見つからない場合は、迷惑メールフォルダを確認してください。",sendCode:"安全なコードを送信",usePassword:"パスワードを使用",useCode:"メールコードを使用",verify:"確認して続行",createAndSignIn:"パスワードを作成してログイン",continuePassword:"パスワードで続行",anotherEmail:"別のメールを使用",wait:"お待ちください…",completing:"安全なログインを完了しています…"},
  ko:{title:"로그인 또는 가입",description:"일회용 코드를 받을 이메일을 입력하세요. 처음 확인된 로그인 시 GreatLoveMeta 계정이 자동 생성됩니다.",quote:"훌륭한 커뮤니티는 참여와 신뢰, 함께하는 발전으로 성장합니다.",back:"홈으로 돌아가기",meta:"GREATLOVE 메타버스 커뮤니티",eyebrow:"안전한 계정 접근",continueText:"이메일 코드 또는 비밀번호로 계속하세요. 확인된 새 이메일로 계정이 자동 생성됩니다.",email:"이메일 주소",password:"비밀번호",createPassword:"비밀번호 만들기",confirmPassword:"비밀번호 확인",code:"일회용 코드",spam:"받은편지함에 코드가 없으면 스팸 또는 정크 폴더를 확인하세요.",sendCode:"보안 코드 보내기",usePassword:"비밀번호 사용",useCode:"이메일 코드 사용",verify:"확인하고 계속",createAndSignIn:"비밀번호 만들고 로그인",continuePassword:"비밀번호로 계속",anotherEmail:"다른 이메일 사용",wait:"잠시만 기다려 주세요…",completing:"안전한 로그인을 완료하는 중…"},
  es:{title:"Iniciar sesión o unirse",description:"Introduce tu correo para recibir un código de un solo uso. El primer acceso verificado crea automáticamente tu cuenta GreatLoveMeta.",quote:"Las grandes comunidades crecen con participación, confianza y progreso compartido.",back:"Volver al inicio",meta:"COMUNIDAD DEL METAVERSO GREATLOVE",eyebrow:"ACCESO SEGURO A LA CUENTA",continueText:"Continúa con un código por correo o contraseña. Un correo nuevo verificado crea tu cuenta automáticamente.",email:"Correo electrónico",password:"Contraseña",createPassword:"Crear contraseña",confirmPassword:"Confirmar contraseña",code:"Código de un solo uso",spam:"Si no ves el correo con el código, revisa Spam o correo no deseado.",sendCode:"Enviar código seguro",usePassword:"Usar contraseña",useCode:"Usar código por correo",verify:"Verificar y continuar",createAndSignIn:"Crear contraseña e iniciar sesión",continuePassword:"Continuar con contraseña",anotherEmail:"Usar otro correo",wait:"Espera…",completing:"Completando el acceso seguro…"},
  fr:{title:"Se connecter ou rejoindre",description:"Saisissez votre e-mail pour recevoir un code à usage unique. La première connexion vérifiée crée automatiquement votre compte GreatLoveMeta.",quote:"Les grandes communautés grandissent grâce à la participation, la confiance et au progrès partagé.",back:"Retour à l’accueil",meta:"COMMUNAUTÉ DU MÉTAVERS GREATLOVE",eyebrow:"ACCÈS SÉCURISÉ AU COMPTE",continueText:"Continuez avec un code e-mail ou un mot de passe. Un nouvel e-mail vérifié crée automatiquement votre compte.",email:"Adresse e-mail",password:"Mot de passe",createPassword:"Créer un mot de passe",confirmPassword:"Confirmer le mot de passe",code:"Code à usage unique",spam:"Si le message contenant le code n’est pas dans la boîte de réception, vérifiez les indésirables.",sendCode:"Envoyer le code sécurisé",usePassword:"Utiliser le mot de passe",useCode:"Utiliser un code e-mail",verify:"Vérifier et continuer",createAndSignIn:"Créer le mot de passe et se connecter",continuePassword:"Continuer avec le mot de passe",anotherEmail:"Utiliser un autre e-mail",wait:"Veuillez patienter…",completing:"Connexion sécurisée en cours…"},
  de:{title:"Anmelden oder beitreten",description:"Gib deine E-Mail-Adresse für einen Einmalcode ein. Die erste bestätigte Anmeldung erstellt automatisch dein GreatLoveMeta-Konto.",quote:"Große Gemeinschaften wachsen durch Beteiligung, Vertrauen und gemeinsamen Fortschritt.",back:"Zur Startseite",meta:"GREATLOVE-METAVERSE-COMMUNITY",eyebrow:"SICHERER KONTOZUGANG",continueText:"Mit E-Mail-Code oder Passwort fortfahren. Eine neue bestätigte E-Mail erstellt automatisch dein Konto.",email:"E-Mail-Adresse",password:"Passwort",createPassword:"Passwort erstellen",confirmPassword:"Passwort bestätigen",code:"Einmalcode",spam:"Wenn die Code-E-Mail nicht im Posteingang ist, prüfe Spam oder Junk.",sendCode:"Sicheren Code senden",usePassword:"Passwort verwenden",useCode:"E-Mail-Code verwenden",verify:"Bestätigen und fortfahren",createAndSignIn:"Passwort erstellen und anmelden",continuePassword:"Mit Passwort fortfahren",anotherEmail:"Andere E-Mail verwenden",wait:"Bitte warten…",completing:"Sichere Anmeldung wird abgeschlossen…"},
  ru:{title:"Войти или присоединиться",description:"Введите электронную почту, чтобы получить одноразовый код. Первый подтверждённый вход автоматически создаст аккаунт GreatLoveMeta.",quote:"Сильные сообщества растут благодаря участию, доверию и общему прогрессу.",back:"На главную",meta:"СООБЩЕСТВО МЕТАВСЕЛЕННОЙ GREATLOVE",eyebrow:"БЕЗОПАСНЫЙ ДОСТУП",continueText:"Продолжите с кодом из письма или паролем. Новый подтверждённый адрес автоматически создаст аккаунт.",email:"Электронная почта",password:"Пароль",createPassword:"Создать пароль",confirmPassword:"Подтвердить пароль",code:"Одноразовый код",spam:"Если письма с кодом нет во входящих, проверьте папку «Спам».",sendCode:"Отправить защищённый код",usePassword:"Использовать пароль",useCode:"Использовать код из письма",verify:"Подтвердить и продолжить",createAndSignIn:"Создать пароль и войти",continuePassword:"Продолжить с паролем",anotherEmail:"Другая почта",wait:"Подождите…",completing:"Завершаем безопасный вход…"},
  it:{title:"Accedi o unisciti",description:"Inserisci l’e-mail per ricevere un codice monouso. Il primo accesso verificato crea automaticamente il tuo account GreatLoveMeta.",quote:"Le grandi comunità crescono con partecipazione, fiducia e progresso condiviso.",back:"Torna alla home",meta:"COMUNITÀ DEL METAVERSO GREATLOVE",eyebrow:"ACCESSO SICURO ALL’ACCOUNT",continueText:"Continua con un codice e-mail o una password. Una nuova e-mail verificata crea automaticamente l’account.",email:"Indirizzo e-mail",password:"Password",createPassword:"Crea password",confirmPassword:"Conferma password",code:"Codice monouso",spam:"Se non trovi l’e-mail con il codice, controlla Spam o Posta indesiderata.",sendCode:"Invia codice sicuro",usePassword:"Usa password",useCode:"Usa codice e-mail",verify:"Verifica e continua",createAndSignIn:"Crea password e accedi",continuePassword:"Continua con password",anotherEmail:"Usa un’altra e-mail",wait:"Attendi…",completing:"Accesso sicuro in completamento…"},
  pt:{title:"Entrar ou participar",description:"Digite seu e-mail para receber um código de uso único. O primeiro acesso verificado cria automaticamente sua conta GreatLoveMeta.",quote:"Grandes comunidades crescem com participação, confiança e progresso compartilhado.",back:"Voltar ao início",meta:"COMUNIDADE DO METAVERSO GREATLOVE",eyebrow:"ACESSO SEGURO À CONTA",continueText:"Continue com código por e-mail ou senha. Um novo e-mail verificado cria sua conta automaticamente.",email:"Endereço de e-mail",password:"Senha",createPassword:"Criar senha",confirmPassword:"Confirmar senha",code:"Código de uso único",spam:"Se o e-mail com o código não estiver na caixa de entrada, verifique Spam ou Lixo eletrônico.",sendCode:"Enviar código seguro",usePassword:"Usar senha",useCode:"Usar código por e-mail",verify:"Verificar e continuar",createAndSignIn:"Criar senha e entrar",continuePassword:"Continuar com senha",anotherEmail:"Usar outro e-mail",wait:"Aguarde…",completing:"Concluindo acesso seguro…"},
  ar:{title:"تسجيل الدخول أو الانضمام",description:"أدخل بريدك الإلكتروني للحصول على رمز لمرة واحدة. ينشئ أول دخول موثّق حساب GreatLoveMeta تلقائيًا.",quote:"تنمو المجتمعات العظيمة بالمشاركة والثقة والتقدم المشترك.",back:"العودة إلى الرئيسية",meta:"مجتمع عالم GREATLOVE الافتراضي",eyebrow:"وصول آمن إلى الحساب",continueText:"تابع برمز البريد الإلكتروني أو كلمة المرور. ينشئ البريد الجديد الموثّق حسابك تلقائيًا.",email:"البريد الإلكتروني",password:"كلمة المرور",createPassword:"إنشاء كلمة مرور",confirmPassword:"تأكيد كلمة المرور",code:"رمز لمرة واحدة",spam:"إذا لم تجد رسالة الرمز في الوارد، فتحقق من مجلد الرسائل غير المرغوب فيها.",sendCode:"إرسال رمز آمن",usePassword:"استخدام كلمة المرور",useCode:"استخدام رمز البريد",verify:"تحقق وتابع",createAndSignIn:"أنشئ كلمة المرور وسجّل الدخول",continuePassword:"المتابعة بكلمة المرور",anotherEmail:"استخدام بريد آخر",wait:"يرجى الانتظار…",completing:"جارٍ إكمال الدخول الآمن…"},
  hi:{title:"साइन इन करें या जुड़ें",description:"एक बार उपयोग होने वाला कोड पाने के लिए ईमेल दर्ज करें। पहला सत्यापित साइन-इन आपका GreatLoveMeta खाता अपने आप बनाता है।",quote:"महान समुदाय सहभागिता, भरोसे और साझा प्रगति से बढ़ते हैं।",back:"होम पर वापस",meta:"GREATLOVE मेटावर्स समुदाय",eyebrow:"सुरक्षित खाता पहुँच",continueText:"ईमेल कोड या पासवर्ड से आगे बढ़ें। नया सत्यापित ईमेल आपका खाता अपने आप बनाता है।",email:"ईमेल पता",password:"पासवर्ड",createPassword:"पासवर्ड बनाएँ",confirmPassword:"पासवर्ड की पुष्टि करें",code:"एक बार का कोड",spam:"अगर कोड वाला ईमेल इनबॉक्स में नहीं है, तो Spam या Junk फ़ोल्डर देखें।",sendCode:"सुरक्षित कोड भेजें",usePassword:"पासवर्ड उपयोग करें",useCode:"ईमेल कोड उपयोग करें",verify:"सत्यापित करें और आगे बढ़ें",createAndSignIn:"पासवर्ड बनाएँ और साइन इन करें",continuePassword:"पासवर्ड से आगे बढ़ें",anotherEmail:"दूसरा ईमेल उपयोग करें",wait:"कृपया प्रतीक्षा करें…",completing:"सुरक्षित साइन-इन पूरा हो रहा है…"}
};

export const authInterfaceCopyFor=(lang:SiteLanguage)=>copies[lang];
